// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Category struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type CommentReaction struct {
	ID         uuid.UUID    `db:"id" json:"id"`
	CommentID  uuid.UUID    `db:"comment_id" json:"comment_id"`
	UserID     uuid.UUID    `db:"user_id" json:"user_id"`
	ReactionID uuid.UUID    `db:"reaction_id" json:"reaction_id"`
	CreatedAt  sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type Community struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	CreatorID         uuid.NullUUID  `db:"creator_id" json:"creator_id"`
	PaymentID         uuid.NullUUID  `db:"payment_id" json:"payment_id"`
	InvitedBy         uuid.NullUUID  `db:"invited_by" json:"invited_by"`
	IsCreatePermited  sql.NullBool   `db:"is_create_permited" json:"is_create_permited"`
	Title             sql.NullString `db:"title" json:"title"`
	Slug              string         `db:"slug" json:"slug"`
	Summery           sql.NullString `db:"summery" json:"summery"`
	Description       sql.NullString `db:"description" json:"description"`
	IsFeatures        sql.NullBool   `db:"is_features" json:"is_features"`
	CoverImageUrl     sql.NullString `db:"cover_image_url" json:"cover_image_url"`
	ProfileImageUrl   sql.NullString `db:"profile_image_url" json:"profile_image_url"`
	ThumbnailVideoUrl sql.NullString `db:"thumbnail_video_url" json:"thumbnail_video_url"`
	Visibility        sql.NullString `db:"visibility" json:"visibility"`
	InviteOnly        sql.NullBool   `db:"invite_only" json:"invite_only"`
	ApprovalRequired  sql.NullBool   `db:"approval_required" json:"approval_required"`
	MemberLimit       sql.NullInt32  `db:"member_limit" json:"member_limit"`
	MembersCount      sql.NullInt32  `db:"members_count" json:"members_count"`
	Tags              []string       `db:"tags" json:"tags"`
	Location          sql.NullString `db:"location" json:"location"`
	IsPaid            sql.NullBool   `db:"is_paid" json:"is_paid"`
	Price             sql.NullString `db:"price" json:"price"`
	BillingCycle      sql.NullString `db:"billing_cycle" json:"billing_cycle"`
	TrialAvailable    sql.NullBool   `db:"trial_available" json:"trial_available"`
	TrialDays         sql.NullInt32  `db:"trial_days" json:"trial_days"`
	Status            sql.NullString `db:"status" json:"status"`
	StartDate         sql.NullTime   `db:"start_date" json:"start_date"`
	EndDate           sql.NullTime   `db:"end_date" json:"end_date"`
	CreatedAt         sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt         sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt         sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type CommunityCategory struct {
	CommunityID uuid.UUID    `db:"community_id" json:"community_id"`
	CategoryID  uuid.UUID    `db:"category_id" json:"category_id"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type CommunityMember struct {
	CommunityID          uuid.UUID      `db:"community_id" json:"community_id"`
	UserID               uuid.UUID      `db:"user_id" json:"user_id"`
	Status               sql.NullString `db:"status" json:"status"`
	InvitedBy            uuid.NullUUID  `db:"invited_by" json:"invited_by"`
	NotificationsEnabled sql.NullBool   `db:"notifications_enabled" json:"notifications_enabled"`
	LastActivityAt       sql.NullTime   `db:"last_activity_at" json:"last_activity_at"`
	IsBanned             sql.NullBool   `db:"is_banned" json:"is_banned"`
	BanReason            sql.NullString `db:"ban_reason" json:"ban_reason"`
	IsPaid               sql.NullBool   `db:"is_paid" json:"is_paid"`
	PaymentID            uuid.NullUUID  `db:"payment_id" json:"payment_id"`
	IsSubscribe          sql.NullBool   `db:"is_subscribe" json:"is_subscribe"`
	SubscriptionStartAt  sql.NullTime   `db:"subscription_start_at" json:"subscription_start_at"`
	SubscriptionEndAt    sql.NullTime   `db:"subscription_end_at" json:"subscription_end_at"`
	TrialEndAt           sql.NullTime   `db:"trial_end_at" json:"trial_end_at"`
	BillingStatus        sql.NullString `db:"billing_status" json:"billing_status"`
	JoinedAt             sql.NullTime   `db:"joined_at" json:"joined_at"`
	CreatedAt            sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt            sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt            sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type CommunityMessage struct {
	ID            uuid.UUID             `db:"id" json:"id"`
	CommunityID   uuid.UUID             `db:"community_id" json:"community_id"`
	SenderID      uuid.UUID             `db:"sender_id" json:"sender_id"`
	ReceiverID    uuid.UUID             `db:"receiver_id" json:"receiver_id"`
	Content       string                `db:"content" json:"content"`
	Attachments   pqtype.NullRawMessage `db:"attachments" json:"attachments"`
	IsRead        sql.NullBool          `db:"is_read" json:"is_read"`
	ReadAt        sql.NullTime          `db:"read_at" json:"read_at"`
	IsDeleted     sql.NullBool          `db:"is_deleted" json:"is_deleted"`
	IsEdited      sql.NullBool          `db:"is_edited" json:"is_edited"`
	EditedAt      sql.NullTime          `db:"edited_at" json:"edited_at"`
	MessageStatus sql.NullString        `db:"message_status" json:"message_status"`
	CreatedAt     sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type CommunityPost struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	CommunityID   uuid.UUID      `db:"community_id" json:"community_id"`
	UserID        uuid.UUID      `db:"user_id" json:"user_id"`
	Title         sql.NullString `db:"title" json:"title"`
	Content       string         `db:"content" json:"content"`
	MediaUrl      sql.NullString `db:"media_url" json:"media_url"`
	LikesCount    sql.NullInt32  `db:"likes_count" json:"likes_count"`
	CommentsCount sql.NullInt32  `db:"comments_count" json:"comments_count"`
	IsPinned      sql.NullBool   `db:"is_pinned" json:"is_pinned"`
	CreatedAt     sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type CommunityPostComment struct {
	ID            uuid.UUID             `db:"id" json:"id"`
	PostID        uuid.UUID             `db:"post_id" json:"post_id"`
	UserID        uuid.UUID             `db:"user_id" json:"user_id"`
	ParentID      uuid.NullUUID         `db:"parent_id" json:"parent_id"`
	Content       string                `db:"content" json:"content"`
	Attachments   pqtype.NullRawMessage `db:"attachments" json:"attachments"`
	Mentions      []uuid.UUID           `db:"mentions" json:"mentions"`
	IsEdited      sql.NullBool          `db:"is_edited" json:"is_edited"`
	EditedAt      sql.NullTime          `db:"edited_at" json:"edited_at"`
	IsDeleted     sql.NullBool          `db:"is_deleted" json:"is_deleted"`
	DeletedReason sql.NullString        `db:"deleted_reason" json:"deleted_reason"`
	CreatedAt     sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type CommunityUserBlock struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	CommunityID uuid.UUID      `db:"community_id" json:"community_id"`
	BlockerID   uuid.UUID      `db:"blocker_id" json:"blocker_id"`
	BlockedID   uuid.UUID      `db:"blocked_id" json:"blocked_id"`
	Reason      sql.NullString `db:"reason" json:"reason"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type CommunityUserFollow struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	CommunityID  uuid.UUID      `db:"community_id" json:"community_id"`
	FollowerID   uuid.UUID      `db:"follower_id" json:"follower_id"`
	FollowingID  uuid.UUID      `db:"following_id" json:"following_id"`
	IsMuted      sql.NullBool   `db:"is_muted" json:"is_muted"`
	IsBlocked    sql.NullBool   `db:"is_blocked" json:"is_blocked"`
	FollowStatus sql.NullString `db:"follow_status" json:"follow_status"`
	FollowNotes  sql.NullString `db:"follow_notes" json:"follow_notes"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type Course struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	CommunityID uuid.UUID      `db:"community_id" json:"community_id"`
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
	Content     sql.NullString `db:"content" json:"content"`
	IsActive    sql.NullBool   `db:"is_active" json:"is_active"`
	StartDate   sql.NullTime   `db:"start_date" json:"start_date"`
	EndDate     sql.NullTime   `db:"end_date" json:"end_date"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type CourseLesson struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	ModuleID        uuid.UUID      `db:"module_id" json:"module_id"`
	CourseID        uuid.UUID      `db:"course_id" json:"course_id"`
	Title           string         `db:"title" json:"title"`
	VideoUrl        sql.NullString `db:"video_url" json:"video_url"`
	TextContent     sql.NullString `db:"text_content" json:"text_content"`
	SourceUrl       sql.NullString `db:"source_url" json:"source_url"`
	DurationMinutes sql.NullInt32  `db:"duration_minutes" json:"duration_minutes"`
	OrderNum        int32          `db:"order_num" json:"order_num"`
	CreatedAt       sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt       sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type CourseModule struct {
	ID        uuid.UUID    `db:"id" json:"id"`
	CourseID  uuid.UUID    `db:"course_id" json:"course_id"`
	Title     string       `db:"title" json:"title"`
	OrderNum  int32        `db:"order_num" json:"order_num"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type Notification struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	UserID          uuid.UUID      `db:"user_id" json:"user_id"`
	Type            string         `db:"type" json:"type"`
	Title           string         `db:"title" json:"title"`
	Message         string         `db:"message" json:"message"`
	ActionUrl       sql.NullString `db:"action_url" json:"action_url"`
	RelatedID       uuid.NullUUID  `db:"related_id" json:"related_id"`
	RelatedType     sql.NullString `db:"related_type" json:"related_type"`
	DeliveryChannel sql.NullString `db:"delivery_channel" json:"delivery_channel"`
	Priority        sql.NullString `db:"priority" json:"priority"`
	IsRead          sql.NullBool   `db:"is_read" json:"is_read"`
	ReadAt          sql.NullTime   `db:"read_at" json:"read_at"`
	SentAt          sql.NullTime   `db:"sent_at" json:"sent_at"`
	CreatedAt       sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt       sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type Payment struct {
	ID                    uuid.UUID             `db:"id" json:"id"`
	UserID                uuid.UUID             `db:"user_id" json:"user_id"`
	Amount                string                `db:"amount" json:"amount"`
	Currency              sql.NullString        `db:"currency" json:"currency"`
	PaymentStatus         sql.NullString        `db:"payment_status" json:"payment_status"`
	PaymentMethod         sql.NullString        `db:"payment_method" json:"payment_method"`
	StripePaymentIntentID sql.NullString        `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
	TransactionID         sql.NullString        `db:"transaction_id" json:"transaction_id"`
	ReceiptUrl            sql.NullString        `db:"receipt_url" json:"receipt_url"`
	StripeCustomerID      sql.NullString        `db:"stripe_customer_id" json:"stripe_customer_id"`
	StripePaymentMethodID sql.NullString        `db:"stripe_payment_method_id" json:"stripe_payment_method_id"`
	StripeSessionID       sql.NullString        `db:"stripe_session_id" json:"stripe_session_id"`
	Metadata              pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	RelatedType           sql.NullString        `db:"related_type" json:"related_type"`
	RelatedID             uuid.NullUUID         `db:"related_id" json:"related_id"`
	NextRetryAt           sql.NullTime          `db:"next_retry_at" json:"next_retry_at"`
	CreatedAt             sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt             sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt             sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type PostReaction struct {
	ID         uuid.UUID    `db:"id" json:"id"`
	PostID     uuid.UUID    `db:"post_id" json:"post_id"`
	UserID     uuid.UUID    `db:"user_id" json:"user_id"`
	ReactionID uuid.UUID    `db:"reaction_id" json:"reaction_id"`
	CreatedAt  sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type Reaction struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Icon        sql.NullString `db:"icon" json:"icon"`
	Description sql.NullString `db:"description" json:"description"`
	IsActive    sql.NullBool   `db:"is_active" json:"is_active"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type Role struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type SocialLink struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Name        sql.NullString `db:"name" json:"name"`
	Url         sql.NullString `db:"url" json:"url"`
	Icon        sql.NullString `db:"icon" json:"icon"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID                   uuid.UUID             `db:"id" json:"id"`
	RolesID              uuid.NullUUID         `db:"roles_id" json:"roles_id"`
	Email                string                `db:"email" json:"email"`
	Password             sql.NullString        `db:"password" json:"password"`
	FirstName            sql.NullString        `db:"first_name" json:"first_name"`
	LastName             sql.NullString        `db:"last_name" json:"last_name"`
	FullName             sql.NullString        `db:"full_name" json:"full_name"`
	Username             string                `db:"username" json:"username"`
	Phone                sql.NullString        `db:"phone" json:"phone"`
	ProfilePic           sql.NullString        `db:"profile_pic" json:"profile_pic"`
	About                sql.NullString        `db:"about" json:"about"`
	Provider             string                `db:"provider" json:"provider"`
	ProviderID           string                `db:"provider_id" json:"provider_id"`
	IsEmailVerified      sql.NullBool          `db:"is_email_verified" json:"is_email_verified"`
	IsActive             sql.NullBool          `db:"is_active" json:"is_active"`
	LastLoginAt          sql.NullTime          `db:"last_login_at" json:"last_login_at"`
	LastFailedLoginAt    sql.NullTime          `db:"last_failed_login_at" json:"last_failed_login_at"`
	FailedLoginAttempts  sql.NullInt32         `db:"failed_login_attempts" json:"failed_login_attempts"`
	PasswordChangedAt    sql.NullTime          `db:"password_changed_at" json:"password_changed_at"`
	HasAccess            sql.NullBool          `db:"has_access" json:"has_access"`
	TwoFactorEnabled     sql.NullBool          `db:"two_factor_enabled" json:"two_factor_enabled"`
	TwoFactorSecret      sql.NullString        `db:"two_factor_secret" json:"two_factor_secret"`
	TwoFactorBackupCodes pqtype.NullRawMessage `db:"two_factor_backup_codes" json:"two_factor_backup_codes"`
	CreatedAt            sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt            sql.NullTime          `db:"updated_at" json:"updated_at"`
	DeletedAt            sql.NullTime          `db:"deleted_at" json:"deleted_at"`
}

type UserCourseProgress struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	UserID            uuid.UUID      `db:"user_id" json:"user_id"`
	CourseID          uuid.UUID      `db:"course_id" json:"course_id"`
	LessonID          uuid.UUID      `db:"lesson_id" json:"lesson_id"`
	ProgressPercent   sql.NullInt32  `db:"progress_percent" json:"progress_percent"`
	Completed         sql.NullBool   `db:"completed" json:"completed"`
	CompletedAt       sql.NullTime   `db:"completed_at" json:"completed_at"`
	CertificateIssued sql.NullBool   `db:"certificate_issued" json:"certificate_issued"`
	CertificateUrl    sql.NullString `db:"certificate_url" json:"certificate_url"`
	CertificateID     uuid.NullUUID  `db:"certificate_id" json:"certificate_id"`
	Feedback          sql.NullString `db:"feedback" json:"feedback"`
	CreatedAt         sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt         sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt         sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type UserModuleProgress struct {
	ID              uuid.UUID     `db:"id" json:"id"`
	UserID          uuid.UUID     `db:"user_id" json:"user_id"`
	CourseID        uuid.UUID     `db:"course_id" json:"course_id"`
	ModuleID        uuid.UUID     `db:"module_id" json:"module_id"`
	ProgressPercent sql.NullInt32 `db:"progress_percent" json:"progress_percent"`
	Completed       sql.NullBool  `db:"completed" json:"completed"`
	CompletedAt     sql.NullTime  `db:"completed_at" json:"completed_at"`
	CreatedAt       sql.NullTime  `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime  `db:"updated_at" json:"updated_at"`
}
