// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetTopUsers(ctx context.Context, db DBTX, limit int32) ([]GetTopUsersRow, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, db DBTX, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, db DBTX, username string) (GetUserByUsernameRow, error)
	GetUserRecommendations(ctx context.Context, db DBTX, arg GetUserRecommendationsParams) ([]GetUserRecommendationsRow, error)
	GetUserStats(ctx context.Context, db DBTX, id uuid.UUID) (GetUserStatsRow, error)
	GetUsersByActivityRange(ctx context.Context, db DBTX, arg GetUsersByActivityRangeParams) ([]GetUsersByActivityRangeRow, error)
	GetUsersByCommunity(ctx context.Context, db DBTX, arg GetUsersByCommunityParams) ([]GetUsersByCommunityRow, error)
	GetUsersByRole(ctx context.Context, db DBTX, arg GetUsersByRoleParams) ([]GetUsersByRoleRow, error)
	ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]ListUsersRow, error)
	SearchUsers(ctx context.Context, db DBTX, arg SearchUsersParams) ([]SearchUsersRow, error)
}

var _ Querier = (*Queries)(nil)
