import type { Metadata } from "next";
import "../assets/styles/globals.css";
import { ThemeProvider } from "@/themes/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased w-full min-h-screen bg-black text-white relative`}>
        <main className="flex-1 relative z-10"> {children}</main>
      </body>
    </html>
  );
}
