/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard error response payload returned by the API
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     * Stable machine-readable error code
     * @type {string}
     * @memberof ApiErrorResponse
     */
    code: string;
    /**
     * Optional structured details for clients (e.g., validation issues)
     * @type {any}
     * @memberof ApiErrorResponse
     */
    details?: any | null;
    /**
     * Human-readable error message
     * @type {string}
     * @memberof ApiErrorResponse
     */
    message: string;
    /**
     * Timestamp at which the error was produced
     * @type {Date}
     * @memberof ApiErrorResponse
     */
    timestamp: Date;
    /**
     * Optional request/trace correlation id
     * @type {string}
     * @memberof ApiErrorResponse
     */
    traceId?: string | null;
}

/**
 * Check if a given object implements the ApiErrorResponse interface.
 */
export function instanceOfApiErrorResponse(value: object): value is ApiErrorResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ApiErrorResponseFromJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseFromJSONTyped(json, false);
}

export function ApiErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'],
        'timestamp': (new Date(json['timestamp'])),
        'traceId': json['trace_id'] == null ? undefined : json['trace_id'],
    };
}

export function ApiErrorResponseToJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseToJSONTyped(json, false);
}

export function ApiErrorResponseToJSONTyped(value?: ApiErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
        'timestamp': ((value['timestamp']).toISOString()),
        'trace_id': value['traceId'],
    };
}

