/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseModule
 */
export interface CourseModule {
    /**
     * 
     * @type {string}
     * @memberof CourseModule
     */
    courseId: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseModule
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CourseModule
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CourseModule
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CourseModule
     */
    position: number;
    /**
     * 
     * @type {string}
     * @memberof CourseModule
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseModule
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the CourseModule interface.
 */
export function instanceOfCourseModule(value: object): value is CourseModule {
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CourseModuleFromJSON(json: any): CourseModule {
    return CourseModuleFromJSONTyped(json, false);
}

export function CourseModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseModule {
    if (json == null) {
        return json;
    }
    return {
        
        'courseId': json['course_id'],
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'position': json['position'],
        'title': json['title'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function CourseModuleToJSON(json: any): CourseModule {
    return CourseModuleToJSONTyped(json, false);
}

export function CourseModuleToJSONTyped(value?: CourseModule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'course_id': value['courseId'],
        'created_at': ((value['createdAt']).toISOString()),
        'description': value['description'],
        'id': value['id'],
        'position': value['position'],
        'title': value['title'],
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
    };
}

