/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCourseRequest
 */
export interface CreateCourseRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCourseRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseRequest
     */
    duration: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseRequest
     */
    excerpt?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCourseRequest
     */
    featured: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateCourseRequest
     */
    original_price?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCourseRequest
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseRequest
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseRequest
     */
    thumbnail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseRequest
     */
    title: string;
}

/**
 * Check if a given object implements the CreateCourseRequest interface.
 */
export function instanceOfCreateCourseRequest(value: object): value is CreateCourseRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('featured' in value) || value['featured'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateCourseRequestFromJSON(json: any): CreateCourseRequest {
    return CreateCourseRequestFromJSONTyped(json, false);
}

export function CreateCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCourseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'duration': json['duration'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'featured': json['featured'],
        'original_price': json['original_price'] == null ? undefined : json['original_price'],
        'price': json['price'],
        'slug': json['slug'],
        'thumbnail': json['thumbnail'] == null ? undefined : json['thumbnail'],
        'title': json['title'],
    };
}

export function CreateCourseRequestToJSON(json: any): CreateCourseRequest {
    return CreateCourseRequestToJSONTyped(json, false);
}

export function CreateCourseRequestToJSONTyped(value?: CreateCourseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'duration': value['duration'],
        'excerpt': value['excerpt'],
        'featured': value['featured'],
        'original_price': value['original_price'],
        'price': value['price'],
        'slug': value['slug'],
        'thumbnail': value['thumbnail'],
        'title': value['title'],
    };
}

