/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLessonRequest
 */
export interface CreateLessonRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateLessonRequest
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonRequest
     */
    duration: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateLessonRequest
     */
    isFree: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonRequest
     */
    moduleId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateLessonRequest
     */
    position: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreateLessonRequest
     */
    published: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonRequest
     */
    videoUrl?: string | null;
}

/**
 * Check if a given object implements the CreateLessonRequest interface.
 */
export function instanceOfCreateLessonRequest(value: object): value is CreateLessonRequest {
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('isFree' in value) || value['isFree'] === undefined) return false;
    if (!('moduleId' in value) || value['moduleId'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('published' in value) || value['published'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateLessonRequestFromJSON(json: any): CreateLessonRequest {
    return CreateLessonRequestFromJSONTyped(json, false);
}

export function CreateLessonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLessonRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'description': json['description'] == null ? undefined : json['description'],
        'duration': json['duration'],
        'isFree': json['is_free'],
        'moduleId': json['module_id'],
        'position': json['position'],
        'published': json['published'],
        'title': json['title'],
        'videoUrl': json['video_url'] == null ? undefined : json['video_url'],
    };
}

export function CreateLessonRequestToJSON(json: any): CreateLessonRequest {
    return CreateLessonRequestToJSONTyped(json, false);
}

export function CreateLessonRequestToJSONTyped(value?: CreateLessonRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'description': value['description'],
        'duration': value['duration'],
        'is_free': value['isFree'],
        'module_id': value['moduleId'],
        'position': value['position'],
        'published': value['published'],
        'title': value['title'],
        'video_url': value['videoUrl'],
    };
}

