/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateModuleRequest
 */
export interface CreateModuleRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateModuleRequest
     */
    course_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateModuleRequest
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateModuleRequest
     */
    position: number;
    /**
     * 
     * @type {string}
     * @memberof CreateModuleRequest
     */
    title: string;
}

/**
 * Check if a given object implements the CreateModuleRequest interface.
 */
export function instanceOfCreateModuleRequest(value: object): value is CreateModuleRequest {
    if (!('course_id' in value) || value['course_id'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateModuleRequestFromJSON(json: any): CreateModuleRequest {
    return CreateModuleRequestFromJSONTyped(json, false);
}

export function CreateModuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateModuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'course_id': json['course_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'position': json['position'],
        'title': json['title'],
    };
}

export function CreateModuleRequestToJSON(json: any): CreateModuleRequest {
    return CreateModuleRequestToJSONTyped(json, false);
}

export function CreateModuleRequestToJSONTyped(value?: CreateModuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'course_id': value['course_id'],
        'description': value['description'],
        'position': value['position'],
        'title': value['title'],
    };
}

