/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Instructor
 */
export interface Instructor {
    /**
     * 
     * @type {string}
     * @memberof Instructor
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Instructor
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Instructor
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Instructor
     */
    username: string;
}

/**
 * Check if a given object implements the Instructor interface.
 */
export function instanceOfInstructor(value: object): value is Instructor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function InstructorFromJSON(json: any): Instructor {
    return InstructorFromJSONTyped(json, false);
}

export function InstructorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Instructor {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'id': json['id'],
        'username': json['username'],
    };
}

export function InstructorToJSON(json: any): Instructor {
    return InstructorToJSONTyped(json, false);
}

export function InstructorToJSONTyped(value?: Instructor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar_url': value['avatarUrl'],
        'full_name': value['fullName'],
        'id': value['id'],
        'username': value['username'],
    };
}

