/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Lesson
 */
export interface Lesson {
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    content?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Lesson
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    duration: string;
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof Lesson
     */
    is_free: boolean;
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    module_id: string;
    /**
     * 
     * @type {number}
     * @memberof Lesson
     */
    position: number;
    /**
     * 
     * @type {boolean}
     * @memberof Lesson
     */
    published: boolean;
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof Lesson
     */
    updated_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Lesson
     */
    video_url?: string | null;
}

/**
 * Check if a given object implements the Lesson interface.
 */
export function instanceOfLesson(value: object): value is Lesson {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('is_free' in value) || value['is_free'] === undefined) return false;
    if (!('module_id' in value) || value['module_id'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('published' in value) || value['published'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function LessonFromJSON(json: any): Lesson {
    return LessonFromJSONTyped(json, false);
}

export function LessonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Lesson {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'created_at': (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'duration': json['duration'],
        'id': json['id'],
        'is_free': json['is_free'],
        'module_id': json['module_id'],
        'position': json['position'],
        'published': json['published'],
        'title': json['title'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'video_url': json['video_url'] == null ? undefined : json['video_url'],
    };
}

export function LessonToJSON(json: any): Lesson {
    return LessonToJSONTyped(json, false);
}

export function LessonToJSONTyped(value?: Lesson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'created_at': ((value['created_at']).toISOString()),
        'description': value['description'],
        'duration': value['duration'],
        'id': value['id'],
        'is_free': value['is_free'],
        'module_id': value['module_id'],
        'position': value['position'],
        'published': value['published'],
        'title': value['title'],
        'updated_at': value['updated_at'] == null ? undefined : ((value['updated_at'] as any).toISOString()),
        'video_url': value['video_url'],
    };
}

