/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    access_token: string;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    expires_in: number;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    refresh_token: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    token_type: string;
    /**
     * 
     * @type {UserResponse}
     * @memberof LoginResponse
     */
    user: UserResponse;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
    if (!('access_token' in value) || value['access_token'] === undefined) return false;
    if (!('expires_in' in value) || value['expires_in'] === undefined) return false;
    if (!('refresh_token' in value) || value['refresh_token'] === undefined) return false;
    if (!('token_type' in value) || value['token_type'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access_token': json['access_token'],
        'expires_in': json['expires_in'],
        'refresh_token': json['refresh_token'],
        'token_type': json['token_type'],
        'user': UserResponseFromJSON(json['user']),
    };
}

export function LoginResponseToJSON(json: any): LoginResponse {
    return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(value?: LoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['access_token'],
        'expires_in': value['expires_in'],
        'refresh_token': value['refresh_token'],
        'token_type': value['token_type'],
        'user': UserResponseToJSON(value['user']),
    };
}

