/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OkResponse
 */
export interface OkResponse {
    /**
     * 
     * @type {boolean}
     * @memberof OkResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the OkResponse interface.
 */
export function instanceOfOkResponse(value: object): value is OkResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function OkResponseFromJSON(json: any): OkResponse {
    return OkResponseFromJSONTyped(json, false);
}

export function OkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
    };
}

export function OkResponseToJSON(json: any): OkResponse {
    return OkResponseToJSONTyped(json, false);
}

export function OkResponseToJSONTyped(value?: OkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
    };
}

