/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination metadata
 * @export
 * @interface PageMeta
 */
export interface PageMeta {
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    per_page: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    total_pages: number;
}

/**
 * Check if a given object implements the PageMeta interface.
 */
export function instanceOfPageMeta(value: object): value is PageMeta {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('per_page' in value) || value['per_page'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('total_pages' in value) || value['total_pages'] === undefined) return false;
    return true;
}

export function PageMetaFromJSON(json: any): PageMeta {
    return PageMetaFromJSONTyped(json, false);
}

export function PageMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'per_page': json['per_page'],
        'total': json['total'],
        'total_pages': json['total_pages'],
    };
}

export function PageMetaToJSON(json: any): PageMeta {
    return PageMetaToJSONTyped(json, false);
}

export function PageMetaToJSONTyped(value?: PageMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'per_page': value['per_page'],
        'total': value['total'],
        'total_pages': value['total_pages'],
    };
}

