/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination query for list endpoints
 * @export
 * @interface PaginationQuery
 */
export interface PaginationQuery {
    /**
     * 1-based page index
     * @type {number}
     * @memberof PaginationQuery
     */
    page?: number | null;
    /**
     * Items per page
     * @type {number}
     * @memberof PaginationQuery
     */
    per_page?: number | null;
}

/**
 * Check if a given object implements the PaginationQuery interface.
 */
export function instanceOfPaginationQuery(value: object): value is PaginationQuery {
    return true;
}

export function PaginationQueryFromJSON(json: any): PaginationQuery {
    return PaginationQueryFromJSONTyped(json, false);
}

export function PaginationQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'per_page': json['per_page'] == null ? undefined : json['per_page'],
    };
}

export function PaginationQueryToJSON(json: any): PaginationQuery {
    return PaginationQueryToJSONTyped(json, false);
}

export function PaginationQueryToJSONTyped(value?: PaginationQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'per_page': value['per_page'],
    };
}

