/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendOtpRequest
 */
export interface ResendOtpRequest {
    /**
     * 
     * @type {string}
     * @memberof ResendOtpRequest
     */
    email: string;
}

/**
 * Check if a given object implements the ResendOtpRequest interface.
 */
export function instanceOfResendOtpRequest(value: object): value is ResendOtpRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ResendOtpRequestFromJSON(json: any): ResendOtpRequest {
    return ResendOtpRequestFromJSONTyped(json, false);
}

export function ResendOtpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendOtpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ResendOtpRequestToJSON(json: any): ResendOtpRequest {
    return ResendOtpRequestToJSONTyped(json, false);
}

export function ResendOtpRequestToJSONTyped(value?: ResendOtpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

