/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    address_line1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    address_line2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    avatar_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    country?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateUserRequest
     */
    date_of_birth?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    facebook_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    first_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    github_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    instagram_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    last_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    linkedin_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    locale?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserRequest
     */
    marketing_opt_in?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    postal_code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    secondary_email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    twitter_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    website_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    youtube_url?: string | null;
}

/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(value: object): value is UpdateUserRequest {
    return true;
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestFromJSONTyped(json, false);
}

export function UpdateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address_line1': json['address_line1'] == null ? undefined : json['address_line1'],
        'address_line2': json['address_line2'] == null ? undefined : json['address_line2'],
        'avatar_url': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : (new Date(json['date_of_birth'])),
        'facebook_url': json['facebook_url'] == null ? undefined : json['facebook_url'],
        'first_name': json['first_name'] == null ? undefined : json['first_name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'github_url': json['github_url'] == null ? undefined : json['github_url'],
        'instagram_url': json['instagram_url'] == null ? undefined : json['instagram_url'],
        'last_name': json['last_name'] == null ? undefined : json['last_name'],
        'linkedin_url': json['linkedin_url'] == null ? undefined : json['linkedin_url'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'marketing_opt_in': json['marketing_opt_in'] == null ? undefined : json['marketing_opt_in'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'postal_code': json['postal_code'] == null ? undefined : json['postal_code'],
        'secondary_email': json['secondary_email'] == null ? undefined : json['secondary_email'],
        'state': json['state'] == null ? undefined : json['state'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'twitter_url': json['twitter_url'] == null ? undefined : json['twitter_url'],
        'username': json['username'] == null ? undefined : json['username'],
        'website_url': json['website_url'] == null ? undefined : json['website_url'],
        'youtube_url': json['youtube_url'] == null ? undefined : json['youtube_url'],
    };
}

export function UpdateUserRequestToJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestToJSONTyped(json, false);
}

export function UpdateUserRequestToJSONTyped(value?: UpdateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address_line1': value['address_line1'],
        'address_line2': value['address_line2'],
        'avatar_url': value['avatar_url'],
        'bio': value['bio'],
        'city': value['city'],
        'country': value['country'],
        'date_of_birth': value['date_of_birth'] == null ? undefined : ((value['date_of_birth'] as any).toISOString().substring(0,10)),
        'facebook_url': value['facebook_url'],
        'first_name': value['first_name'],
        'gender': value['gender'],
        'github_url': value['github_url'],
        'instagram_url': value['instagram_url'],
        'last_name': value['last_name'],
        'linkedin_url': value['linkedin_url'],
        'locale': value['locale'],
        'marketing_opt_in': value['marketing_opt_in'],
        'phone': value['phone'],
        'postal_code': value['postal_code'],
        'secondary_email': value['secondary_email'],
        'state': value['state'],
        'timezone': value['timezone'],
        'twitter_url': value['twitter_url'],
        'username': value['username'],
        'website_url': value['website_url'],
        'youtube_url': value['youtube_url'],
    };
}

