/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    addressLine1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    addressLine2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    country?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateUserRequest
     */
    dateOfBirth?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    facebookUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    githubUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    instagramUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    linkedinUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    locale?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserRequest
     */
    marketingOptIn?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    postalCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    secondaryEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    twitterUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    websiteUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    youtubeUrl?: string | null;
}

/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(value: object): value is UpdateUserRequest {
    return true;
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestFromJSONTyped(json, false);
}

export function UpdateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'addressLine1': json['address_line1'] == null ? undefined : json['address_line1'],
        'addressLine2': json['address_line2'] == null ? undefined : json['address_line2'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'dateOfBirth': json['date_of_birth'] == null ? undefined : (new Date(json['date_of_birth'])),
        'facebookUrl': json['facebook_url'] == null ? undefined : json['facebook_url'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'githubUrl': json['github_url'] == null ? undefined : json['github_url'],
        'instagramUrl': json['instagram_url'] == null ? undefined : json['instagram_url'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'linkedinUrl': json['linkedin_url'] == null ? undefined : json['linkedin_url'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'marketingOptIn': json['marketing_opt_in'] == null ? undefined : json['marketing_opt_in'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'postalCode': json['postal_code'] == null ? undefined : json['postal_code'],
        'secondaryEmail': json['secondary_email'] == null ? undefined : json['secondary_email'],
        'state': json['state'] == null ? undefined : json['state'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'twitterUrl': json['twitter_url'] == null ? undefined : json['twitter_url'],
        'username': json['username'] == null ? undefined : json['username'],
        'websiteUrl': json['website_url'] == null ? undefined : json['website_url'],
        'youtubeUrl': json['youtube_url'] == null ? undefined : json['youtube_url'],
    };
}

export function UpdateUserRequestToJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestToJSONTyped(json, false);
}

export function UpdateUserRequestToJSONTyped(value?: UpdateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address_line1': value['addressLine1'],
        'address_line2': value['addressLine2'],
        'avatar_url': value['avatarUrl'],
        'bio': value['bio'],
        'city': value['city'],
        'country': value['country'],
        'date_of_birth': value['dateOfBirth'] == null ? undefined : ((value['dateOfBirth'] as any).toISOString().substring(0,10)),
        'facebook_url': value['facebookUrl'],
        'first_name': value['firstName'],
        'gender': value['gender'],
        'github_url': value['githubUrl'],
        'instagram_url': value['instagramUrl'],
        'last_name': value['lastName'],
        'linkedin_url': value['linkedinUrl'],
        'locale': value['locale'],
        'marketing_opt_in': value['marketingOptIn'],
        'phone': value['phone'],
        'postal_code': value['postalCode'],
        'secondary_email': value['secondaryEmail'],
        'state': value['state'],
        'timezone': value['timezone'],
        'twitter_url': value['twitterUrl'],
        'username': value['username'],
        'website_url': value['websiteUrl'],
        'youtube_url': value['youtubeUrl'],
    };
}

