/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateLessonRequest
 */
export interface UpdateLessonRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonRequest
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonRequest
     */
    duration?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateLessonRequest
     */
    isFree?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateLessonRequest
     */
    position?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateLessonRequest
     */
    published?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonRequest
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonRequest
     */
    videoUrl?: string | null;
}

/**
 * Check if a given object implements the UpdateLessonRequest interface.
 */
export function instanceOfUpdateLessonRequest(value: object): value is UpdateLessonRequest {
    return true;
}

export function UpdateLessonRequestFromJSON(json: any): UpdateLessonRequest {
    return UpdateLessonRequestFromJSONTyped(json, false);
}

export function UpdateLessonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLessonRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'description': json['description'] == null ? undefined : json['description'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'isFree': json['is_free'] == null ? undefined : json['is_free'],
        'position': json['position'] == null ? undefined : json['position'],
        'published': json['published'] == null ? undefined : json['published'],
        'title': json['title'] == null ? undefined : json['title'],
        'videoUrl': json['video_url'] == null ? undefined : json['video_url'],
    };
}

export function UpdateLessonRequestToJSON(json: any): UpdateLessonRequest {
    return UpdateLessonRequestToJSONTyped(json, false);
}

export function UpdateLessonRequestToJSONTyped(value?: UpdateLessonRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'description': value['description'],
        'duration': value['duration'],
        'is_free': value['isFree'],
        'position': value['position'],
        'published': value['published'],
        'title': value['title'],
        'video_url': value['videoUrl'],
    };
}

