/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateModuleRequest
 */
export interface UpdateModuleRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateModuleRequest
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateModuleRequest
     */
    position?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateModuleRequest
     */
    title?: string | null;
}

/**
 * Check if a given object implements the UpdateModuleRequest interface.
 */
export function instanceOfUpdateModuleRequest(value: object): value is UpdateModuleRequest {
    return true;
}

export function UpdateModuleRequestFromJSON(json: any): UpdateModuleRequest {
    return UpdateModuleRequestFromJSONTyped(json, false);
}

export function UpdateModuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateModuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'position': json['position'] == null ? undefined : json['position'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function UpdateModuleRequestToJSON(json: any): UpdateModuleRequest {
    return UpdateModuleRequestToJSONTyped(json, false);
}

export function UpdateModuleRequestToJSONTyped(value?: UpdateModuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'position': value['position'],
        'title': value['title'],
    };
}

