/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCourseRequest
 */
export interface UpdateCourseRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    duration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    excerpt?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCourseRequest
     */
    featured?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateCourseRequest
     */
    lessons?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateCourseRequest
     */
    originalPrice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateCourseRequest
     */
    price?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCourseRequest
     */
    published?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateCourseRequest
     */
    students?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    thumbnail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    title?: string | null;
}

/**
 * Check if a given object implements the UpdateCourseRequest interface.
 */
export function instanceOfUpdateCourseRequest(value: object): value is UpdateCourseRequest {
    return true;
}

export function UpdateCourseRequestFromJSON(json: any): UpdateCourseRequest {
    return UpdateCourseRequestFromJSONTyped(json, false);
}

export function UpdateCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCourseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'featured': json['featured'] == null ? undefined : json['featured'],
        'lessons': json['lessons'] == null ? undefined : json['lessons'],
        'originalPrice': json['original_price'] == null ? undefined : json['original_price'],
        'price': json['price'] == null ? undefined : json['price'],
        'published': json['published'] == null ? undefined : json['published'],
        'students': json['students'] == null ? undefined : json['students'],
        'thumbnail': json['thumbnail'] == null ? undefined : json['thumbnail'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function UpdateCourseRequestToJSON(json: any): UpdateCourseRequest {
    return UpdateCourseRequestToJSONTyped(json, false);
}

export function UpdateCourseRequestToJSONTyped(value?: UpdateCourseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'duration': value['duration'],
        'excerpt': value['excerpt'],
        'featured': value['featured'],
        'lessons': value['lessons'],
        'original_price': value['originalPrice'],
        'price': value['price'],
        'published': value['published'],
        'students': value['students'],
        'thumbnail': value['thumbnail'],
        'title': value['title'],
    };
}

