/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfile
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfile
     */
    isActive: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfile
     */
    isBlocked: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    username: string;
}

/**
 * Check if a given object implements the UserProfile interface.
 */
export function instanceOfUserProfile(value: object): value is UserProfile {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('isBlocked' in value) || value['isBlocked'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserProfileFromJSON(json: any): UserProfile {
    return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'createdAt': (new Date(json['created_at'])),
        'email': json['email'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'id': json['id'],
        'isActive': json['is_active'],
        'isBlocked': json['is_blocked'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'role': json['role'],
        'username': json['username'],
    };
}

export function UserProfileToJSON(json: any): UserProfile {
    return UserProfileToJSONTyped(json, false);
}

export function UserProfileToJSONTyped(value?: UserProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar_url': value['avatarUrl'],
        'created_at': ((value['createdAt']).toISOString()),
        'email': value['email'],
        'first_name': value['firstName'],
        'full_name': value['fullName'],
        'id': value['id'],
        'is_active': value['isActive'],
        'is_blocked': value['isBlocked'],
        'last_name': value['lastName'],
        'role': value['role'],
        'username': value['username'],
    };
}

