/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    avatar_url?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfile
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    first_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    full_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfile
     */
    is_active: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfile
     */
    is_blocked: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    last_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    username: string;
}

/**
 * Check if a given object implements the UserProfile interface.
 */
export function instanceOfUserProfile(value: object): value is UserProfile {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('is_active' in value) || value['is_active'] === undefined) return false;
    if (!('is_blocked' in value) || value['is_blocked'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserProfileFromJSON(json: any): UserProfile {
    return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar_url': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'created_at': (new Date(json['created_at'])),
        'email': json['email'],
        'first_name': json['first_name'] == null ? undefined : json['first_name'],
        'full_name': json['full_name'] == null ? undefined : json['full_name'],
        'id': json['id'],
        'is_active': json['is_active'],
        'is_blocked': json['is_blocked'],
        'last_name': json['last_name'] == null ? undefined : json['last_name'],
        'role': json['role'],
        'username': json['username'],
    };
}

export function UserProfileToJSON(json: any): UserProfile {
    return UserProfileToJSONTyped(json, false);
}

export function UserProfileToJSONTyped(value?: UserProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar_url': value['avatar_url'],
        'created_at': ((value['created_at']).toISOString()),
        'email': value['email'],
        'first_name': value['first_name'],
        'full_name': value['full_name'],
        'id': value['id'],
        'is_active': value['is_active'],
        'is_blocked': value['is_blocked'],
        'last_name': value['last_name'],
        'role': value['role'],
        'username': value['username'],
    };
}

