/* tslint:disable */
/* eslint-disable */
/**
 * execute_academy API
 * REST API for execute_academy. See category, product, auth, and user endpoints.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyOtpRequest
 */
export interface VerifyOtpRequest {
    /**
     * 
     * @type {string}
     * @memberof VerifyOtpRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyOtpRequest
     */
    email: string;
}

/**
 * Check if a given object implements the VerifyOtpRequest interface.
 */
export function instanceOfVerifyOtpRequest(value: object): value is VerifyOtpRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function VerifyOtpRequestFromJSON(json: any): VerifyOtpRequest {
    return VerifyOtpRequestFromJSONTyped(json, false);
}

export function VerifyOtpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyOtpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'email': json['email'],
    };
}

export function VerifyOtpRequestToJSON(json: any): VerifyOtpRequest {
    return VerifyOtpRequestToJSONTyped(json, false);
}

export function VerifyOtpRequestToJSONTyped(value?: VerifyOtpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'email': value['email'],
    };
}

